# Generated by Django 5.0.4 on 2024-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_location_type_event_place_event_venue_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
