# Generated by Django 5.0.4 on 2024-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_attendees_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
