# Generated by Django 5.0.4 on 2024-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
    ]
