# Generated by Django 5.0.4 on 2024-06-30 09:09

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0010_groupmessage_file_alter_chatgroup_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
