# Generated by Django 5.0.4 on 2024-04-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='headline',
        ),
    ]
