# Generated by Django 5.0.4 on 2024-05-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='youtube_link',
            new_name='personal_link',
        ),
    ]
