# Generated by Django 5.0.4 on 2024-06-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='senderName',
        ),
    ]
