# Generated by Django 5.0.4 on 2024-07-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_eventmoderator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmoderator',
            name='moderation_history',
        ),
        migrations.CreateModel(
            name='ModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_description', models.TextField()),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='users.eventmoderator')),
            ],
        ),
    ]
