# Generated by Django 5.0.4 on 2024-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_eventmoderator_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
