# Generated by Django 5.0.4 on 2024-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_eventorganizer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorganizer',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
