# Generated by Django 5.0.4 on 2024-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_eventorganizer_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
