# Generated by Django 5.0.4 on 2024-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_eventorganizer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmoderator',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='moderators'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='organizers'),
        ),
    ]
