# Generated by Django 5.0.4 on 2024-06-26 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AddField(
            model_name='room',
            name='user_online',
            field=models.ManyToManyField(blank=True, related_name='online_in_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
