# Generated by Django 5.0.4 on 2024-06-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_message_options_room_user_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_online',
            new_name='users_online',
        ),
    ]
