# Generated by Django 5.0.4 on 2024-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
